### ISSUE TITLE
Potential naming conflict

### ISSUE THREAD

**Issue by fanninpm** [0xd4d/iced#122]
A few redditors have pointed out the fact that the name of this project conflicts with that of [a particular GUI crate,](https://github.com/hecrj/iced) which has probably been around longer than this project has.

**Comment by Symbai** [comment]
That could only be an issue when both are disassemblers which is not the case. Even companies can share a name when they are doing different stuff. And many companies share their name already without its being a legal issue. If your only argument is that both share the same name, then go ahead and try convincing Apple to change their name as its conflicts with a fruit name that has been around longer than their product name 🤷‍♂️

**Comment by 0xd4d** [comment]
I don't think this will confuse anyone since they have different names on crates.io and each crate's description + README clearly explains what it is and how to add it to your cargo.toml.

> which has probably been around longer than this project has.

FYI, it's easy to check this since both are on github, so there's no reason to guess. (hint: this project is older)
