### ISSUE TITLE
Assembler decoder reading pass the instructions

### ISSUE THREAD

**Issue by kkokosa** [0xd4d/iced#123]
The problem is, I don't know how to properly dissasemble code assembled by Iced.

First of all, I'm using very simple wrappers around native memory to read/write:

```cs
internal class MemoryCodeWriter : CodeWriter
{
    private readonly IntPtr _ptr;
    private int _offset;

    public MemoryCodeWriter(IntPtr ptr)
    {
        _ptr = ptr;
    }

    public int Length => _offset;

    public override void WriteByte(byte value)
    {
        Marshal.WriteByte(_ptr, _offset, value);
        _offset++;
        Console.Write(".");
    }
}
```

when assembling very simple code:

```cs
asm.Reset();
asm.push(rbp);
asm.mov(rbp, rsp);
asm.sub(rsp, 32);
asm.add(rcx, 16);
asm.call((ulong)_funcPtr);
asm.mov(rsp, rbp);
asm.pop(rbp);
asm.ret();

var codeWriter = new MemoryCodeWriter((IntPtr)codePtr);
asm.Assemble(codeWriter, (ulong)codePtr);
```

the result should be 23 bytes of instructions, but `codeWriter.Length` shows 32 because of additional data written by `Iced.Intel.BlockEncoderInternal.Block.WriteData` method. So the [Disassemble (decode and format instructions)](https://github.com/0xd4d/iced/blob/master/src/csharp/Intel/README.md#disassemble-decode-and-format-instructions) example from documentation tries to interpret this additional bytes as instructions, producing garbage:

```asm
000001DA30B80000 55                    push rbp
000001DA30B80001 4889E5                mov rbp,rsp
000001DA30B80004 4883EC20              sub rsp,20h
000001DA30B80008 4883C110              add rcx,10h
000001DA30B8000C FF1506000000          call qword [rel 1DA30B80018h]
000001DA30B80012 4889EC                mov rsp,rbp
000001DA30B80015 5D                    pop rbp
000001DA30B80016 C3                    ret
000001DA30B80017 CC                    int3
000001DA30B80018 44310C11              xor [rcx+rdx],r9d
000001DA30B8001C FA                    cli
000001DA30B8001D 7F00                  jg short 000001DA30B8001Fh
000001DA30B8001F 00
```

How can I get the "real" number of bytes of instructions, to be used by the `Decoder`?

**Comment by 0xd4d** [comment]
The problem is that this is 64-bit code and you use `CALL rel32` to call some code. This instruction has a 32-bit signed displacement and if your code is too far away, it can't be used. Iced will fix this for you by default which is what you see above: the data after the last instruction is what it's referencing which holds the address of the target.

You can disable this (and get an exception because the call target is too far away) with `BlockEncoderOptions.DontFixBranches`.

Or you can change your code and use `rax`:

```C#
asm.mov(rax,_funcPtr);
asm.call(rax);
```

> How can I get the "real" number of bytes of instructions, to be used by the Decoder?

All the data is important to execute the code. If you only want to disassemble it and not show the extra (required) data, you can pass in `BlockEncoderOptions.ReturnNewInstructionOffsets` to get the offsets of all encoded instructions. The last entry in that array has the offset of the RET instruction. Decode it to get its length (should be 1 in this case) and you know the size of the code before the data.

**Comment by kkokosa** [comment]
Awesome, thank you! My mistake. It works perfectly with the proper call. And with the `ReturnNewInstructionOffset` I will be able to present data correctly, if necessary.
