### ISSUE TITLE
Add Span<T> and Memory<T> support

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#32]
Would be nice if ByteArrayCodeReader also accepts span/memory

**Comment by 0xd4d** [comment]
`Span<T>` can only be stored on the stack, not inside GC objects.

In order to use `Span<T>` you would have to pass it to `Decode()` and all decoder handlers. It wouldn't be possible to use a generic `CodeReader` without duplicating all methods that read a byte from the instruction stream.

The code won't be much faster either. There would be one less virtual call every time a byte was read.
