### ISSUE TITLE
IP relative memory operand is too far away 

### ISSUE THREAD

**Issue by 25rtsregre** [0xd4d/iced#47]
Hello 0xd4d,

I am currently using iced for dissembling and reassembling x64 code however upon what i think is the LEA instruction i am receiving the following limitation exception

System.InvalidProgramException: 'IP relative memory operand is too far away and isn't currently supported'

is this something that is planned to be added soon?

Kind Regards

**Comment by 0xd4d** [comment]
It has low priority since some registers could be needed to emulate it.

There's a workaround and that is to make sure you allocate your code close to the patched code. Use `VirtualAllocEx(hProcess, addr, ALLOC_SIZE, MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READ)` where `addr` is an address +/-2GB from the instructions. Just keep calling `VirtualAllocEx()` with increasing and decreasing addresses until it succeeds (or until `addr` is too far away).

Here's dnSpy's code: https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Debugger/dnSpy.Debugger/AntiAntiDebug/ProcessMemoryBlockAllocator.cs#L73

**Comment by 25rtsregre** [comment]
Awesome thank you
