### ISSUE TITLE
Update `test` operand order to match dumpbin

### ISSUE THREAD

**Issue by Symbai** [0xd4d/iced#53]
Masm mode

input:
`{ 0x41, 0x85, 0x9D, 0xF8, 0x6B, 0x06, 0x00 }`
iced:
`test ebx,[r13+66BF8]`
expected:
`test [r13+66BF8],ebx`

Assemblers I've tried don't accept Iced's output including XEDParse which says to support MASM. Disassemblers I've tried gave me the expected output.

**Comment by 0xd4d** [comment]
All assemblers should accept any operand order of the `TEST` instruction since it only reads both values, eg. `x & y` is the same as `y & x`.

I don't remember why I chose that order if it's MASM, I assume dumpbin used it with that input, but the current dumpbin doesn't do it unless it's the `XCHG` instruction.

**Comment by Symbai** [comment]
Assemblers I've tested which does NOT accept the order of Iced result:
XEDParse (x64dbg)
asmjit (x64dbg)
Shell-storm.org

Only Keystone accepts it. On Nasm its the "correct" order. Just masm where its flipped. If you dont plan to change it can you tell me how I can change it myself?

**Comment by 0xd4d** [comment]
I try to match the output of the official disassemblers and in masm's case it's dumpbin, so I'll update it (even though both orders are correct and accepted by masm).

If those assemblers don't support that order, you should report it to them.

Patch the generator: https://github.com/0xd4d/iced/blob/master/Generator/Formatters/Masm/CtorInfos.cs#L298-L301 change reverse2 to probably Normal1_1
