### ISSUE TITLE
Zero-Sized-Instruction for better label in assembler?

### ISSUE THREAD

**Issue by xoofx** [0xd4d/iced#62]
Hey, 
So after the work #60 I'm thinking of improving label by adding support for zero-sized instruction.

The idea is that instead of the hack we have in the assembler where the label is assigned to the next instruction, it would allow to emit a label without necessarily a following instruction. The label would be directly this zero-sized instruction.

It can be useful for example, if you want to access from the end of a data region, but want to put a label at the very end, you can't do that with the assembler, unless you emit a dummy db/dw/db/dq at the end.

Do you think it is possible to add that? How much trouble/how to proceed? Any guidance welcome, I could try a PR on top of the rust branch for adding that if you want.

**Comment by 0xd4d** [comment]
I think the `BlockEncoder` would need some work since it assumes all instructions are encoded to at least one byte. When a branch instruction checks if the target is within this block or another one, it uses the IP of the target instruction, but if there are zero-sized instructions, more than one instruction could be found since the zero-sized instruction and the following instruction would have the same IP. The code calls `blockEncoder.GetTarget()` to get the target so that method would probably need to be updated.

If this zero-sized instruction is always the last instruction in the block, it might work with minimal updates to `BlockEncoder` since there won't be any instructions with the same IP address.

If you decide to add it, add it somewhere at the beginning of the `Code` enum, eg. after `DeclareQword` or before `DeclareByte`. I want all non-instructions at the beginning so it's easy to figure out if it's a real instruction or not. :)

The `Encoder` would special case this instruction, just like it already special cases `Code.INVALID` (see `OpCodeHandlers` .cctor). Some new class is created. It would have to set some flag similar to how `DeclareByte/etc` handlers do so no prefixes/etc is written to the output (must write exactly zero bytes).

**Comment by 0xd4d** [comment]
If you decide to do this, at least these would need updated (most are simple one-line updates).  The unit tests will report other stuff.

Generator:

- InstructionMemorySizesTable.cs
- InstructionOpCountsTable.cs
- MnemonicsTable.cs
- OpCodeInfoTable.cs
- CodeEnum.cs
- MnemonicEnum.cs
- {Gas,Intel,Masm,Nasm}\CtorInfos.cs
- InstrInfoTable.cs

src\UnitTests
- Encoder\OpCodeInfos.txt
- InstructionInfo\InstructionInfoTest_64.txt

**Comment by xoofx** [comment]
After thinking about it, gonna drop this idea. It would be bad to occupy an instruction slot for just a label, the existing solution is more lightweight.
